"""Account report generation — PowerPoint summary built with python-pptx.

The KPI/figures come from the loaded data; the narrative "executive summary"
bullets are generated by the user's local Claude Code CLI (best-effort — if it
is unavailable the deck is still produced without the narrative).
"""
from __future__ import annotations

import subprocess
from datetime import date
from io import BytesIO

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pptx import Presentation
from pptx.util import Inches, Pt
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.chat import _claude_cmd
from app.core.config import settings
from app.core.database import get_session
from app.models import Client, Contract, Financial, Opportunity, Resource

router = APIRouter(prefix="/api/reports", tags=["reports"])


def _eur(v: float) -> str:
    return f"€ {v:,.0f}".replace(",", ".")


async def _summary(session: AsyncSession) -> dict:
    contracts = (await session.scalars(select(Contract))).all()
    financials = (await session.scalars(select(Financial))).all()
    resources = (await session.scalars(select(Resource))).all()
    opps = (await session.scalars(select(Opportunity))).all()
    clients = (await session.scalars(select(Client))).all()

    rev = sum((f.revenues_actual or 0) + (f.revenues_forecast or 0) for f in financials)
    cost = sum(
        (f.payroll_costs_actual or 0) + (f.payroll_costs_forecast or 0)
        + (f.non_payroll_costs_actual or 0) + (f.non_payroll_costs_forecast or 0)
        + (f.capital_charges_actual or 0) + (f.capital_charges_forecast or 0)
        for f in financials
    )
    ci = rev - cost
    pipeline: dict[str, float] = {}
    for o in opps:
        pipeline[o.stage] = pipeline.get(o.stage, 0.0) + (o.estimated_value or 0.0)
    return {
        "clients": [c.name for c in clients],
        "contracts": len(contracts),
        "resources": len(resources),
        "opportunities": len(opps),
        "revenues": rev,
        "costs": cost,
        "ci": ci,
        "ci_pct": (ci / rev) if rev else 0.0,
        "pipeline_total": sum(o.estimated_value or 0 for o in opps),
        "pipeline_by_stage": pipeline,
    }


def _narrative(s: dict) -> list[str]:
    """Ask the local Claude Code CLI for a short executive summary (best-effort)."""
    cmd = _claude_cmd(settings.chat_model)
    if cmd is None:
        return []
    lang = "italiano" if settings.language == "it" else "English"
    prompt = (
        f"Scrivi un executive summary in {lang} per una presentazione dirigenziale "
        f"dell'account. Massimo 5 bullet concisi, uno per riga, senza titoli né "
        f"markdown, basandoti SOLO su questi dati:\n"
        f"- Clienti: {', '.join(s['clients']) or 'n/d'}\n"
        f"- Contratti: {s['contracts']}, Risorse: {s['resources']}, Opportunità: {s['opportunities']}\n"
        f"- Ricavi: {_eur(s['revenues'])}, Costi: {_eur(s['costs'])}, "
        f"CI: {_eur(s['ci'])} ({s['ci_pct']*100:.1f}%)\n"
        f"- Pipeline totale: {_eur(s['pipeline_total'])}; per stage: "
        f"{', '.join(f'{k}={_eur(v)}' for k, v in s['pipeline_by_stage'].items())}\n"
    )
    try:
        proc = subprocess.run(cmd, input=prompt, capture_output=True, text=True, timeout=120)
    except (subprocess.TimeoutExpired, OSError):
        return []
    if proc.returncode != 0:
        return []
    lines = [ln.strip(" -•\t") for ln in proc.stdout.splitlines() if ln.strip()]
    return lines[:6]


def _build_pptx(s: dict, bullets: list[str]) -> BytesIO:
    prs = Presentation()
    title_txt = "PM Control Center — Account Summary"
    subtitle = f"{', '.join(s['clients']) or 'Account'} · {date.today().isoformat()}"

    # Slide 1 — title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title_txt
    slide.placeholders[1].text = subtitle

    # Slide 2 — KPI table
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "KPI"
    kpis = [
        ("Ricavi (YTD+FCST)", _eur(s["revenues"])),
        ("Costi totali", _eur(s["costs"])),
        ("Contribution Income", _eur(s["ci"])),
        ("CI %", f"{s['ci_pct']*100:.1f}%"),
        ("Contratti", str(s["contracts"])),
        ("Risorse", str(s["resources"])),
        ("Opportunità", str(s["opportunities"])),
        ("Pipeline", _eur(s["pipeline_total"])),
    ]
    rows = len(kpis) + 1
    table = slide.shapes.add_table(rows, 2, Inches(0.6), Inches(1.4), Inches(8.5),
                                   Inches(0.4 * rows)).table
    table.cell(0, 0).text = "Metrica"
    table.cell(0, 1).text = "Valore"
    for i, (k, v) in enumerate(kpis, start=1):
        table.cell(i, 0).text = k
        table.cell(i, 1).text = v
    for r in range(rows):
        for cidx in range(2):
            for p in table.cell(r, cidx).text_frame.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(12)

    # Slide 3 — executive summary (Claude narrative, if any)
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Executive Summary"
    tf = slide.placeholders[1].text_frame
    if bullets:
        tf.text = bullets[0]
        for b in bullets[1:]:
            p = tf.add_paragraph()
            p.text = b
    else:
        tf.text = "Riepilogo non disponibile (Claude Code non raggiungibile)."

    # Slide 4 — pipeline by stage
    if s["pipeline_by_stage"]:
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = "Pipeline per stage"
        items = list(s["pipeline_by_stage"].items())
        table = slide.shapes.add_table(len(items) + 1, 2, Inches(0.6), Inches(1.4),
                                       Inches(6), Inches(0.4 * (len(items) + 1))).table
        table.cell(0, 0).text = "Stage"
        table.cell(0, 1).text = "Valore"
        for i, (k, v) in enumerate(items, start=1):
            table.cell(i, 0).text = k
            table.cell(i, 1).text = _eur(v)

    out = BytesIO()
    prs.save(out)
    out.seek(0)
    return out


@router.post("/account-ppt")
async def account_ppt(session: AsyncSession = Depends(get_session)):
    s = await _summary(session)
    bullets = _narrative(s)
    pptx_io = _build_pptx(s, bullets)
    fname = f"Account_Summary_{date.today().isoformat()}.pptx"
    return StreamingResponse(
        pptx_io,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
