"""Account report generation — a management-grade PowerPoint summary.

Figures come from the loaded data; the narrative (executive summary, highlights,
recommendations) is generated by the user's local Claude Code CLI using the
**Opus** model for quality. A two-step UX is supported:

* POST /api/reports/account-ppt/plan  -> Claude describes how the deck will look
  (shown in a confirmation chat before generating)
* POST /api/reports/account-ppt       -> builds and returns the .pptx
"""
from __future__ import annotations

import json
import subprocess
from datetime import date
from io import BytesIO

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Emu, Inches, Pt
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.chat import _claude_cmd
from app.core.database import get_session
from app.models import Client, Contract, Financial, Opportunity, Resource

router = APIRouter(prefix="/api/reports", tags=["reports"])

PPT_MODEL = "opus-5"  # Opus 5 for management-grade presentation quality

# --- palette ---
PURPLE = RGBColor(0x7C, 0x3A, 0xED)
PURPLE_DARK = RGBColor(0x4C, 0x1D, 0x95)
INK = RGBColor(0x1E, 0x29, 0x3B)
SLATE = RGBColor(0x64, 0x74, 0x8B)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GREEN = RGBColor(0x10, 0xB9, 0x81)
AMBER = RGBColor(0xF5, 0x9E, 0x0B)
RED = RGBColor(0xEF, 0x44, 0x44)
LIGHT = RGBColor(0xF1, 0xF5, 0xF9)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def _eur(v: float) -> str:
    return f"€ {v:,.0f}".replace(",", ".")


# --------------------------------------------------------------------------- #
# data
# --------------------------------------------------------------------------- #
async def _summary(session: AsyncSession) -> dict:
    contracts = (await session.scalars(select(Contract))).all()
    financials = (await session.scalars(select(Financial))).all()
    resources = (await session.scalars(select(Resource))).all()
    opps = (await session.scalars(select(Opportunity))).all()
    clients = (await session.scalars(select(Client))).all()

    rev = sum((f.revenues_actual or 0) + (f.revenues_forecast or 0) for f in financials)
    cost = sum(
        (f.payroll_costs_actual or 0) + (f.payroll_costs_forecast or 0)
        + (f.non_payroll_costs_actual or 0) + (f.non_payroll_costs_forecast or 0)
        + (f.capital_charges_actual or 0) + (f.capital_charges_forecast or 0)
        for f in financials
    )
    ci = rev - cost
    won = sum(o.estimated_value or 0 for o in opps if o.stage == "CloseWon")
    pipeline: dict[str, float] = {}
    for o in opps:
        if o.stage not in ("CloseWon", "CloseLost"):
            pipeline[o.stage] = pipeline.get(o.stage, 0.0) + (o.estimated_value or 0.0)
    return {
        "clients": [c.name for c in clients],
        "contracts": len(contracts),
        "resources": len(resources),
        "opportunities": len(opps),
        "revenues": rev,
        "costs": cost,
        "ci": ci,
        "ci_pct": (ci / rev) if rev else 0.0,
        "won": won,
        "pipeline_total": sum(pipeline.values()),
        "pipeline_by_stage": pipeline,
    }


# --------------------------------------------------------------------------- #
# Claude (Opus)
# --------------------------------------------------------------------------- #
def _claude(prompt: str, timeout: int = 150) -> str | None:
    cmd = _claude_cmd(PPT_MODEL)
    if cmd is None:
        return None
    try:
        proc = subprocess.run(cmd, input=prompt, capture_output=True, text=True, timeout=timeout)
    except (subprocess.TimeoutExpired, OSError):
        return None
    return proc.stdout.strip() if proc.returncode == 0 else None


def _data_block(s: dict) -> str:
    return (
        f"- Clienti: {', '.join(s['clients']) or 'n/d'}\n"
        f"- Contratti: {s['contracts']}, Risorse: {s['resources']}, Opportunità: {s['opportunities']}\n"
        f"- Ricavi: {_eur(s['revenues'])}, Costi: {_eur(s['costs'])}, "
        f"CI: {_eur(s['ci'])} ({s['ci_pct']*100:.1f}%)\n"
        f"- Vinto (CloseWon): {_eur(s['won'])}; Pipeline aperta: {_eur(s['pipeline_total'])} "
        f"({', '.join(f'{k}={_eur(v)}' for k, v in s['pipeline_by_stage'].items()) or 'n/d'})\n"
    )


def _plan(s: dict, instructions: str) -> str:
    extra = f"\nIndicazioni dell'utente da rispettare:\n{instructions}\n" if instructions else ""
    prompt = (
        "Sei un consulente che prepara una presentazione dirigenziale (per il management) "
        "di sintesi di un account. Descrivi in modo sintetico e professionale COME sarà "
        "strutturata la presentazione: elenca le slide previste e, per ciascuna, 1 riga di "
        "contenuto. Massimo ~10 righe. Non generare la presentazione, solo il piano. "
        "Chiudi chiedendo conferma o modifiche. Basati su questi dati:\n"
        + _data_block(s) + extra
    )
    return _claude(prompt, timeout=90) or (
        "Struttura proposta:\n"
        "1) Copertina (account, data)\n2) KPI chiave (Ricavi, Costi, CI, CI%)\n"
        "3) Executive summary\n4) Andamento economico (grafico Ricavi/Costi/CI)\n"
        "5) Pipeline per stage\n6) Raccomandazioni\n\nConfermi o vuoi modifiche?"
        "\n\n(Nota: Claude Code non raggiungibile — piano di default.)"
    )


def _narrative(s: dict, instructions: str) -> dict:
    extra = f"\nIndicazioni dell'utente:\n{instructions}\n" if instructions else ""
    prompt = (
        "Genera i CONTENUTI TESTUALI per una presentazione dirigenziale di sintesi "
        "dell'account, in italiano, tono professionale e sintetico. Rispondi SOLO con "
        "JSON valido, senza testo attorno, con questa forma:\n"
        '{"subtitle": "...", "executive_summary": ["..."], "highlights": ["..."], '
        '"recommendations": ["..."]}\n'
        "Ogni lista 3-5 voci brevi. Basati esclusivamente su questi dati:\n"
        + _data_block(s) + extra
    )
    raw = _claude(prompt, timeout=150)
    if raw:
        try:
            start, end = raw.find("{"), raw.rfind("}")
            if start >= 0 and end > start:
                data = json.loads(raw[start : end + 1])
                return {
                    "subtitle": data.get("subtitle", ""),
                    "executive_summary": data.get("executive_summary", [])[:6],
                    "highlights": data.get("highlights", [])[:6],
                    "recommendations": data.get("recommendations", [])[:6],
                }
        except (json.JSONDecodeError, TypeError):
            pass
    return {"subtitle": "", "executive_summary": [], "highlights": [], "recommendations": []}


# --------------------------------------------------------------------------- #
# pptx building blocks
# --------------------------------------------------------------------------- #
def _blank(prs: Presentation):
    return prs.slides.add_slide(prs.slide_layouts[6])


def _rect(slide, x, y, w, h, color, shape=MSO_SHAPE.RECTANGLE):
    sp = slide.shapes.add_shape(shape, x, y, w, h)
    sp.fill.solid()
    sp.fill.fore_color.rgb = color
    sp.line.fill.background()
    sp.shadow.inherit = False
    return sp


def _text(slide, x, y, w, h, text, size, color, bold=False, align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return tb


def _bullets(slide, x, y, w, h, title, items, accent):
    _rect(slide, x, y, Inches(0.12), h, accent)
    _text(slide, x + Inches(0.3), y - Inches(0.05), w, Inches(0.5), title, 18, INK, bold=True)
    tb = slide.shapes.add_textbox(x + Inches(0.3), y + Inches(0.5), w - Inches(0.4), h - Inches(0.5))
    tf = tb.text_frame
    tf.word_wrap = True
    for i, it in enumerate(items or ["—"]):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(8)
        run = p.add_run()
        run.text = "•  " + str(it)
        run.font.size = Pt(14)
        run.font.color.rgb = INK


def _title_slide(prs, title, subtitle):
    s = _blank(prs)
    _rect(s, 0, 0, SLIDE_W, SLIDE_H, PURPLE_DARK)
    _rect(s, 0, Inches(5.1), SLIDE_W, Inches(0.12), PURPLE)
    _text(s, Inches(0.9), Inches(2.4), Inches(11.5), Inches(1.6), title, 40, WHITE, bold=True)
    _text(s, Inches(0.95), Inches(4.1), Inches(11), Inches(0.9), subtitle, 18, RGBColor(0xC4, 0xB5, 0xFD))
    _text(s, Inches(0.95), Inches(6.7), Inches(11), Inches(0.5),
          "PM Control Center · Account Review", 12, RGBColor(0x9C, 0xA3, 0xAF))
    return s


def _kpi_slide(prs, s):
    slide = _blank(prs)
    _rect(slide, 0, 0, SLIDE_W, Inches(1.1), PURPLE)
    _text(slide, Inches(0.6), Inches(0.28), Inches(11), Inches(0.6), "KPI dell'account", 26, WHITE, bold=True)
    ci_color = GREEN if s["ci_pct"] >= 0.35 else AMBER if s["ci_pct"] >= 0.30 else RED
    cards = [
        ("Ricavi", _eur(s["revenues"]), PURPLE),
        ("Costi totali", _eur(s["costs"]), SLATE),
        ("Contribution Income", _eur(s["ci"]), PURPLE_DARK),
        ("CI %", f"{s['ci_pct']*100:.1f}%", ci_color),
        ("Contratti", str(s["contracts"]), PURPLE),
        ("Risorse", str(s["resources"]), SLATE),
        ("Vinto (FY)", _eur(s["won"]), GREEN),
        ("Pipeline aperta", _eur(s["pipeline_total"]), AMBER),
    ]
    cols, gap = 4, Inches(0.35)
    cw = (SLIDE_W - Inches(1.2) - gap * (cols - 1)) / cols
    ch = Inches(1.9)
    x0, y0 = Inches(0.6), Inches(1.5)
    for i, (label, value, color) in enumerate(cards):
        r, c = divmod(i, cols)
        x = x0 + c * (cw + gap)
        y = y0 + r * (ch + Inches(0.4))
        card = _rect(slide, x, y, cw, ch, color, MSO_SHAPE.ROUNDED_RECTANGLE)
        tf = card.text_frame
        tf.vertical_anchor = MSO_ANCHOR.MIDDLE
        p = tf.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        run = p.add_run(); run.text = value
        run.font.size = Pt(24); run.font.bold = True; run.font.color.rgb = WHITE
        p2 = tf.add_paragraph(); p2.alignment = PP_ALIGN.CENTER
        run2 = p2.add_run(); run2.text = label
        run2.font.size = Pt(11); run2.font.color.rgb = WHITE
    return slide


def _section_header(slide, title):
    _rect(slide, 0, 0, SLIDE_W, Inches(1.0), PURPLE)
    _text(slide, Inches(0.6), Inches(0.24), Inches(11.5), Inches(0.6), title, 24, WHITE, bold=True)


def _summary_slide(prs, nar):
    slide = _blank(prs)
    _section_header(slide, "Executive Summary")
    _bullets(slide, Inches(0.6), Inches(1.4), Inches(7.6), Inches(5.6),
             "Sintesi", nar["executive_summary"] or ["Riepilogo non disponibile."], PURPLE)
    _bullets(slide, Inches(8.5), Inches(1.4), Inches(4.2), Inches(2.7),
             "Punti di forza", nar["highlights"], GREEN)
    _bullets(slide, Inches(8.5), Inches(4.3), Inches(4.2), Inches(2.7),
             "Raccomandazioni", nar["recommendations"], AMBER)


def _fin_chart_slide(prs, s):
    slide = _blank(prs)
    _section_header(slide, "Andamento economico")
    data = CategoryChartData()
    data.categories = ["Ricavi", "Costi", "CI"]
    data.add_series("EUR", (s["revenues"], s["costs"], s["ci"]))
    gf = slide.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, Inches(0.8), Inches(1.5),
                                Inches(6.0), Inches(5.2), data)
    gf.chart.has_legend = False
    _text(slide, Inches(7.2), Inches(1.8), Inches(5.4), Inches(0.6),
          f"CI% = {s['ci_pct']*100:.1f}%", 20, INK, bold=True)
    target = "≥ 35% (target)" if s["ci_pct"] >= 0.35 else "sotto target 35%"
    _text(slide, Inches(7.2), Inches(2.5), Inches(5.4), Inches(0.6), target, 14, SLATE)
    _text(slide, Inches(7.2), Inches(3.3), Inches(5.4), Inches(2.0),
          f"Ricavi {_eur(s['revenues'])}\nCosti {_eur(s['costs'])}\nCI {_eur(s['ci'])}", 14, INK)


def _pipeline_slide(prs, s):
    if not s["pipeline_by_stage"]:
        return
    slide = _blank(prs)
    _section_header(slide, "Pipeline per stage")
    data = CategoryChartData()
    items = list(s["pipeline_by_stage"].items())
    data.categories = [k for k, _ in items]
    data.add_series("Valore", tuple(v for _, v in items))
    gf = slide.shapes.add_chart(XL_CHART_TYPE.BAR_CLUSTERED, Inches(0.8), Inches(1.5),
                                Inches(11.5), Inches(5.2), data)
    gf.chart.has_legend = True
    gf.chart.legend.position = XL_LEGEND_POSITION.BOTTOM
    gf.chart.legend.include_in_layout = False


def _build(s: dict, nar: dict) -> BytesIO:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    subtitle = nar.get("subtitle") or (
        f"{', '.join(s['clients']) or 'Account'} · {date.today().strftime('%d/%m/%Y')}"
    )
    _title_slide(prs, "Account Summary", subtitle)
    _kpi_slide(prs, s)
    _summary_slide(prs, nar)
    _fin_chart_slide(prs, s)
    _pipeline_slide(prs, s)
    out = BytesIO()
    prs.save(out)
    out.seek(0)
    return out


# --------------------------------------------------------------------------- #
# endpoints
# --------------------------------------------------------------------------- #
class GenRequest(BaseModel):
    instructions: str = ""


@router.post("/account-ppt/plan")
async def account_ppt_plan(req: GenRequest, session: AsyncSession = Depends(get_session)):
    s = await _summary(session)
    return {"plan": _plan(s, req.instructions), "model": PPT_MODEL,
            "available": _claude_cmd(PPT_MODEL) is not None}


@router.post("/account-ppt")
async def account_ppt(req: GenRequest, session: AsyncSession = Depends(get_session)):
    s = await _summary(session)
    nar = _narrative(s, req.instructions)
    pptx_io = _build(s, nar)
    fname = f"Account_Summary_{date.today().isoformat()}.pptx"
    return StreamingResponse(
        pptx_io,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
