"""Account report generation — a management-grade PowerPoint summary.

Figures come from the loaded data; the narrative (executive summary, highlights,
recommendations) is generated by the user's local Claude Code CLI using the
**Opus** model. The deck is built in a template chosen by the user: a built-in
style or an example deck they uploaded (see ``services/ppt_templates.py``).

* GET    /api/reports/templates            -> built-in + uploaded templates (with analysis)
* POST   /api/reports/templates            -> upload an example .pptx (analysed and stored)
* DELETE /api/reports/templates/{id}       -> remove an uploaded template
* POST   /api/reports/account-ppt/plan     -> Claude describes how the deck will look
* POST   /api/reports/account-ppt          -> builds and returns the .pptx
"""
from __future__ import annotations

import json
from datetime import date

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_session
from app.models import Client, Contract, Financial, Opportunity, Resource
from app.services import ppt_templates
from app.services.claude_cli import ask_claude, find_claude
from app.services.ppt_builder import build_deck

router = APIRouter(prefix="/api/reports", tags=["reports"])

PPT_MODEL = "opus"  # Claude Code alias of the latest Opus
DEFAULT_TEMPLATE = "builtin:accenture"


def _eur(v: float) -> str:
    return f"€ {v:,.0f}".replace(",", ".")


async def _summary(session: AsyncSession) -> dict:
    contracts = (await session.scalars(select(Contract))).all()
    financials = (await session.scalars(select(Financial))).all()
    resources = (await session.scalars(select(Resource))).all()
    opps = (await session.scalars(select(Opportunity))).all()
    clients = (await session.scalars(select(Client))).all()

    rev = sum((f.revenues_actual or 0) + (f.revenues_forecast or 0) for f in financials)
    cost = sum(
        (f.payroll_costs_actual or 0) + (f.payroll_costs_forecast or 0)
        + (f.non_payroll_costs_actual or 0) + (f.non_payroll_costs_forecast or 0)
        + (f.capital_charges_actual or 0) + (f.capital_charges_forecast or 0)
        for f in financials
    )
    ci = rev - cost
    won = sum(o.estimated_value or 0 for o in opps if o.stage == "CloseWon")
    pipeline: dict[str, float] = {}
    for o in opps:
        if o.stage not in ("CloseWon", "CloseLost"):
            pipeline[o.stage] = pipeline.get(o.stage, 0.0) + (o.estimated_value or 0.0)
    return {
        "clients": [c.name for c in clients],
        "contracts": len(contracts),
        "resources": len(resources),
        "opportunities": len(opps),
        "revenues": rev,
        "costs": cost,
        "ci": ci,
        "ci_pct": (ci / rev) if rev else 0.0,
        "won": won,
        "pipeline_total": sum(pipeline.values()),
        "pipeline_by_stage": pipeline,
    }


def _data_block(s: dict) -> str:
    return (
        f"- Clienti: {', '.join(s['clients']) or 'n/d'}\n"
        f"- Contratti: {s['contracts']}, Risorse: {s['resources']}, Opportunità: {s['opportunities']}\n"
        f"- Ricavi: {_eur(s['revenues'])}, Costi: {_eur(s['costs'])}, "
        f"CI: {_eur(s['ci'])} ({s['ci_pct']*100:.1f}%, target 35%)\n"
        f"- Vinto (CloseWon): {_eur(s['won'])}; Pipeline aperta: {_eur(s['pipeline_total'])} "
        f"({', '.join(f'{k}={_eur(v)}' for k, v in s['pipeline_by_stage'].items()) or 'n/d'})\n"
    )


def _template_label(template_id: str) -> str:
    if template_id in ppt_templates.BUILTIN:
        return ppt_templates.BUILTIN[template_id]["name"]
    meta = ppt_templates.get_template(template_id)
    return meta["name"] if meta else template_id


async def _plan(s: dict, instructions: str, template_id: str) -> str:
    extra = f"\nIndicazioni dell'utente da rispettare:\n{instructions}\n" if instructions else ""
    prompt = (
        "Sei un consulente che prepara una presentazione dirigenziale (per il management) "
        "di sintesi di un account. Descrivi in modo sintetico e professionale COME sarà "
        "strutturata la presentazione: elenca le slide previste e, per ciascuna, 1 riga di "
        f"contenuto. Stile grafico scelto: '{_template_label(template_id)}'. Massimo ~10 righe. "
        "Non generare la presentazione, solo il piano. Chiudi chiedendo conferma o modifiche. "
        "Basati su questi dati:\n" + _data_block(s) + extra
    )
    result = await ask_claude(prompt, PPT_MODEL, timeout=120)
    if result.ok:
        return result.text
    return (
        "Struttura proposta:\n"
        "1) Copertina (account, data)\n2) KPI chiave (Ricavi, Costi, CI, CCI%)\n"
        "3) Executive summary\n4) Andamento economico (grafico Ricavi/Costi/CI)\n"
        "5) Pipeline per stage\n\nConfermi o vuoi modifiche?"
        f"\n\n(Nota: piano di default — {result.error})"
    )


async def _narrative(s: dict, instructions: str) -> dict:
    extra = f"\nIndicazioni dell'utente:\n{instructions}\n" if instructions else ""
    prompt = (
        "Genera i CONTENUTI TESTUALI per una presentazione dirigenziale di sintesi "
        "dell'account, in italiano, tono professionale e sintetico. Rispondi SOLO con "
        "JSON valido, senza testo attorno, con questa forma:\n"
        '{"subtitle": "...", "executive_summary": ["..."], "highlights": ["..."], '
        '"recommendations": ["..."]}\n'
        "Ogni lista 3-5 voci brevi. Basati esclusivamente su questi dati:\n"
        + _data_block(s) + extra
    )
    result = await ask_claude(prompt, PPT_MODEL, timeout=180)
    if result.ok:
        raw = result.text
        try:
            start, end = raw.find("{"), raw.rfind("}")
            if start >= 0 and end > start:
                data = json.loads(raw[start: end + 1])
                return {
                    "subtitle": data.get("subtitle", ""),
                    "executive_summary": data.get("executive_summary", [])[:6],
                    "highlights": data.get("highlights", [])[:6],
                    "recommendations": data.get("recommendations", [])[:6],
                }
        except (json.JSONDecodeError, TypeError):
            pass
    return {"subtitle": "", "executive_summary": [], "highlights": [], "recommendations": []}


def _check_template(template_id: str) -> str:
    template_id = template_id or DEFAULT_TEMPLATE
    if template_id not in ppt_templates.BUILTIN and ppt_templates.get_template(template_id) is None:
        raise HTTPException(404, "Template non trovato")
    return template_id


# --------------------------------------------------------------------------- #
# templates
# --------------------------------------------------------------------------- #
@router.get("/templates")
async def list_templates():
    return ppt_templates.list_templates()


@router.post("/templates", status_code=201)
async def upload_template(file: UploadFile = File(...)):
    data = await file.read()
    try:
        meta = await run_in_threadpool(ppt_templates.save_template, data, file.filename or "template.pptx")
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    return meta


@router.delete("/templates/{template_id}", status_code=204)
async def delete_template(template_id: str):
    if not ppt_templates.delete_template(template_id):
        raise HTTPException(404, "Template non trovato")


# --------------------------------------------------------------------------- #
# generation
# --------------------------------------------------------------------------- #
class GenRequest(BaseModel):
    instructions: str = ""
    template_id: str = DEFAULT_TEMPLATE


@router.post("/account-ppt/plan")
async def account_ppt_plan(req: GenRequest, session: AsyncSession = Depends(get_session)):
    template_id = _check_template(req.template_id)
    s = await _summary(session)
    return {"plan": await _plan(s, req.instructions, template_id), "model": PPT_MODEL,
            "available": find_claude() is not None}


@router.post("/account-ppt")
async def account_ppt(req: GenRequest, session: AsyncSession = Depends(get_session)):
    template_id = _check_template(req.template_id)
    s = await _summary(session)
    nar = await _narrative(s, req.instructions)
    try:
        pptx_io = await run_in_threadpool(build_deck, template_id, s, nar)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    fname = f"Account_Summary_{date.today().isoformat()}.pptx"
    return StreamingResponse(
        pptx_io,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
